#include "bus_app.hpp"
#include <stdio.h>
#include <string.h>
namespace { constexpr uint32_t BG=0x0F172A,CARD=0x1E293B,TEXT=0xF8FAFC,MUTED=0x94A3B8,ACCENT=0x38BDF8; constexpr lv_coord_t PAD=16; }
static const char *kRouteKeyMap[] = {
    "1", "2", "3", "\n",
    "4", "5", "6", "\n",
    "7", "8", "9", "\n",
    LV_SYMBOL_BACKSPACE, "0", LV_SYMBOL_OK, ""
};
static lv_obj_t *label(lv_obj_t *p,const char *s, const lv_font_t *f=&lv_font_montserrat_16, uint32_t col=TEXT){auto *x=lv_label_create(p);lv_label_set_text(x,s);lv_obj_set_style_text_font(x,f,0);lv_obj_set_style_text_color(x,lv_color_hex(col),0);return x;}
static lv_obj_t *button(lv_obj_t *p,const char *s,void *u){auto *b=lv_btn_create(p);lv_obj_set_style_bg_color(b,lv_color_hex(CARD),0);lv_obj_set_style_radius(b,8,0);lv_obj_add_event_cb(b,BusApp::event_cb,LV_EVENT_CLICKED,u);auto *l=label(b,s);lv_obj_center(l);return b;}
BusApp::BusApp():CrystalApp("Bus",&bus_icon){bus_icon_prepare();}
void BusApp::clear_body(){if(body_)lv_obj_del(body_);body_=lv_obj_create(content_);lv_obj_set_size(body_,lv_pct(100),lv_pct(100));lv_obj_set_style_bg_opa(body_,LV_OPA_TRANSP,0);lv_obj_set_style_border_width(body_,0,0);lv_obj_set_style_pad_all(body_,0,0);}
void BusApp::build_shell(){const lv_area_t a=getVisualArea();root_=lv_obj_create(lv_scr_act());lv_obj_set_size(root_,lv_area_get_width(&a),lv_area_get_height(&a));lv_obj_set_pos(root_,0,0);lv_obj_set_style_bg_color(root_,lv_color_hex(BG),0);lv_obj_set_style_border_width(root_,0,0);lv_obj_clear_flag(root_,LV_OBJ_FLAG_SCROLLABLE);title_=label(root_,"Bus",&lv_font_montserrat_28);lv_obj_align(title_,LV_ALIGN_TOP_LEFT,PAD,10);refresh_=button(root_,LV_SYMBOL_REFRESH,this);lv_obj_set_user_data(refresh_,(void*)6);lv_obj_set_size(refresh_,42,42);lv_obj_align(refresh_,LV_ALIGN_TOP_RIGHT,-PAD,8);content_=lv_obj_create(root_);lv_obj_set_size(content_,lv_pct(100),lv_pct(100));lv_obj_set_pos(content_,0,56);lv_obj_set_style_bg_opa(content_,LV_OPA_TRANSP,0);lv_obj_set_style_border_width(content_,0,0);lv_obj_set_style_pad_hor(content_,PAD,0);lv_obj_set_style_pad_bottom(content_,24,0);clear_body();}
void BusApp::show_favorites(){page_=FAVORITES;if(back_){lv_obj_del(back_);back_=nullptr;}lv_obj_align(title_,LV_ALIGN_TOP_LEFT,PAD,10);lv_label_set_text(title_,"Favorites");clear_body();auto *hint=label(body_,"Your nearby buses",&lv_font_montserrat_20);lv_obj_align(hint,LV_ALIGN_TOP_LEFT,0,12);auto *empty=label(body_,"No saved stops yet\nSearch for a route and save a stop to see live ETAs.",&lv_font_montserrat_16,MUTED);lv_obj_set_width(empty,lv_pct(100));lv_obj_align(empty,LV_ALIGN_TOP_LEFT,0,58);auto *b=button(body_,"Find a route",this);lv_obj_set_user_data(b,(void*)2);lv_obj_set_size(b,150,48);lv_obj_align(b,LV_ALIGN_TOP_MID,0,142);}
void BusApp::show_search(){page_=SEARCH;if(back_)lv_obj_del(back_);back_=button(root_,LV_SYMBOL_LEFT,this);lv_obj_set_user_data(back_,(void*)7);lv_obj_set_size(back_,42,42);lv_obj_align(back_,LV_ALIGN_TOP_LEFT,8,8);lv_obj_align(title_,LV_ALIGN_TOP_LEFT,56,10);lv_label_set_text(title_,"Search");clear_body();route_len_=0;route_input_[0]=0;candidate_count_=0;search_input_=label(body_,"Enter route",&lv_font_montserrat_28);lv_obj_set_width(search_input_,lv_pct(100));lv_obj_set_style_text_align(search_input_,LV_TEXT_ALIGN_CENTER,0);lv_obj_align(search_input_,LV_ALIGN_TOP_LEFT,0,8);auto *keys=lv_btnmatrix_create(body_);lv_btnmatrix_set_map(keys,kRouteKeyMap);lv_obj_set_size(keys,280,236);lv_obj_align(keys,LV_ALIGN_TOP_LEFT,0,52);lv_obj_add_event_cb(keys,event_cb,LV_EVENT_VALUE_CHANGED,this);lv_obj_set_style_bg_color(keys,lv_color_hex(BG),0);lv_obj_set_style_bg_color(keys,lv_color_hex(CARD),LV_PART_ITEMS);lv_obj_set_style_text_color(keys,lv_color_hex(TEXT),LV_PART_ITEMS);letters_=lv_obj_create(body_);lv_obj_set_size(letters_,96,236);lv_obj_align(letters_,LV_ALIGN_TOP_RIGHT,0,52);lv_obj_set_flex_flow(letters_,LV_FLEX_FLOW_COLUMN);lv_obj_set_flex_align(letters_,LV_FLEX_ALIGN_START,LV_FLEX_ALIGN_CENTER,LV_FLEX_ALIGN_CENTER);lv_obj_set_scroll_dir(letters_,LV_DIR_VER);lv_obj_set_scrollbar_mode(letters_,LV_SCROLLBAR_MODE_OFF);lv_obj_set_style_pad_row(letters_,6,0);const char *cs=BUS_ROUTE_CHARSET+10;for(;*cs;cs++){char key[2] = {*cs, 0};auto *b=button(letters_,key,this);lv_obj_set_user_data(b,(void*)(uintptr_t)*cs);lv_obj_set_size(b,64,48);}show_suggestions();}
void BusApp::show_suggestions(){if(suggestions_)lv_obj_del(suggestions_);suggestions_=lv_obj_create(body_);lv_obj_set_size(suggestions_,280,112);lv_obj_align(suggestions_,LV_ALIGN_TOP_LEFT,0,300);lv_obj_set_style_bg_opa(suggestions_,LV_OPA_TRANSP,0);lv_obj_set_style_border_width(suggestions_,0,0);lv_obj_set_style_pad_row(suggestions_,4,0);lv_obj_set_flex_flow(suggestions_,LV_FLEX_FLOW_COLUMN);lv_obj_set_scroll_dir(suggestions_,LV_DIR_VER);lv_obj_set_scrollbar_mode(suggestions_,LV_SCROLLBAR_MODE_OFF);if(candidate_count_==0){auto *empty=label(suggestions_,route_len_?"No matching routes":"Type a route number",&lv_font_montserrat_14,MUTED);lv_obj_align(empty,LV_ALIGN_TOP_LEFT,0,4);return;}for(uint8_t i=0;i<candidate_count_;++i){char text[96];snprintf(text,sizeof(text),"%s   %s -> %s",candidates_[i].route,candidates_[i].orig_en,candidates_[i].dest_en);auto *b=button(suggestions_,text,this);lv_obj_set_user_data(b,(void*)(uintptr_t)(0x100+i));lv_obj_set_size(b,280,48);}}
void BusApp::show_stops(){page_=STOPS;if(back_)lv_obj_del(back_);back_=button(root_,LV_SYMBOL_LEFT,this);lv_obj_set_user_data(back_,(void*)8);lv_obj_set_size(back_,42,42);lv_obj_align(back_,LV_ALIGN_TOP_LEFT,8,8);lv_obj_align(title_,LV_ALIGN_TOP_LEFT,56,10);lv_label_set_text_fmt(title_,"%s - %s",route_.route,route_.dest_en);clear_body();auto *list=lv_list_create(body_);lv_obj_set_size(list,lv_pct(100),lv_pct(100));lv_obj_set_style_bg_opa(list,LV_OPA_TRANSP,0);for(uint16_t i=0;i<stop_count_;i++){auto *b=lv_list_add_btn(list,NULL,stops_[i].name_en);lv_obj_add_event_cb(b,event_cb,LV_EVENT_CLICKED,this);lv_obj_set_user_data(b,(void*)(uintptr_t)i);}auto *near=button(body_,"Find nearest",this);lv_obj_set_user_data(near,(void*)4);lv_obj_align(near,LV_ALIGN_BOTTOM_MID,0,-8);}
void BusApp::show_eta(){page_=ETA;if(back_)lv_obj_del(back_);back_=button(root_,LV_SYMBOL_LEFT,this);lv_obj_set_user_data(back_,(void*)9);lv_obj_set_size(back_,42,42);lv_obj_align(back_,LV_ALIGN_TOP_LEFT,8,8);lv_obj_align(title_,LV_ALIGN_TOP_LEFT,56,10);lv_label_set_text(title_,route_.route);clear_body();auto *name=label(body_,stop_id_,&lv_font_montserrat_20);lv_obj_align(name,LV_ALIGN_TOP_LEFT,0,12);status_=label(body_,"Loading ETA...",&lv_font_montserrat_16,MUTED);lv_obj_align(status_,LV_ALIGN_TOP_LEFT,0,54);latest_request_id_=bus_service_request_eta(stop_id_,route_.route,route_.op,route_.service_type);}
void BusApp::render_eta(const bus_eta_result_t *r){if(!status_||!r)return;char buf[160];if(!r->count)snprintf(buf,sizeof(buf),"No departures scheduled");else snprintf(buf,sizeof(buf),"%ld min\n%ld min\n%ld min",(long)r->entries[0].minutes_left,(long)r->entries[1].minutes_left,(long)r->entries[2].minutes_left);lv_label_set_text(status_,buf);}
void BusApp::append(char c){if(route_len_>=4)return;route_input_[route_len_++]=c;route_input_[route_len_]=0;lv_label_set_text(search_input_,route_input_);submit_route();}
void BusApp::backspace(){if(route_len_==0)return;route_input_[--route_len_]=0;lv_label_set_text(search_input_,route_len_?route_input_:"Enter route");if(route_len_)submit_route();else lv_label_set_text(title_,"Search");}
void BusApp::submit_route(){if(!route_len_){candidate_count_=0;show_suggestions();return;}latest_request_id_=bus_service_request_routes(route_input_);lv_label_set_text(title_,"Search");}
void BusApp::event_cb(lv_event_t *e){auto *a=static_cast<BusApp*>(lv_event_get_user_data(e));if(!a)return;auto *t=lv_event_get_target(e);if(lv_event_get_code(e)==LV_EVENT_VALUE_CHANGED){uint16_t id=lv_btnmatrix_get_selected_btn(t);const char *txt=lv_btnmatrix_get_btn_text(t,id);if(!txt)return;if(strcmp(txt,LV_SYMBOL_BACKSPACE)==0)a->backspace();else if(txt[0]>='0'&&txt[0]<='9')a->append(txt[0]);return;}uintptr_t u=(uintptr_t)lv_obj_get_user_data(t);if(u==6)return;if(u>=0x100&&u<0x108){a->route_=a->candidates_[u-0x100];a->latest_request_id_=bus_service_request_stops(&a->route_);lv_label_set_text(a->title_,"Loading stops...");return;}if(u>=32&&u<128){a->append((char)u);return;}if(u==2){a->show_search();return;}if(u==7){a->show_favorites();return;}if(u==8){a->show_search();return;}if(u==9){a->show_stops();return;}if(a->page_==STOPS){uintptr_t i=(uintptr_t)lv_obj_get_user_data(t);if(i<a->stop_count_){strlcpy(a->stop_id_,a->stops_[i].stop_id,sizeof(a->stop_id_));a->show_eta();}}else if(a->page_==FAVORITES)a->show_search();}
void BusApp::bus_event_cb(const bus_event_t *e,void *u){auto *a=static_cast<BusApp*>(u);if(!a||!e)return;if(e->request_id!=a->latest_request_id_) {if(e->type==BUS_EVT_ROUTE_VARIANTS)bus_service_free(e->data.route_variants.variants);if(e->type==BUS_EVT_STOPS_LIST)bus_service_free(e->data.stops_list.stops);return;}if(e->type==BUS_EVT_ROUTE_VARIANTS){a->candidate_count_=e->data.route_variants.count;for(uint8_t i=0;i<a->candidate_count_;++i)a->candidates_[i]=e->data.route_variants.variants[i];bus_service_free(e->data.route_variants.variants);a->show_suggestions();}else if(e->type==BUS_EVT_STOPS_LIST){if(a->stops_)bus_service_free(a->stops_);a->stops_=e->data.stops_list.stops;a->stop_count_=e->data.stops_list.count;a->show_stops();}else if(e->type==BUS_EVT_ETA)a->render_eta(&e->data.eta.result);}
void BusApp::tick_cb(lv_timer_t *t){auto *a=static_cast<BusApp*>(t->user_data);if(!a)return;bus_event_t e;while(bus_service_poll(&e))bus_event_cb(&e,a);if(a->page_==ETA && ++a->eta_tick_ >= 30){a->eta_tick_=0;a->latest_request_id_=bus_service_request_eta(a->stop_id_,a->route_.route,a->route_.op,a->route_.service_type);}}
bool BusApp::onCreate(){build_shell();bus_service_init();bus_service_set_listener(nullptr,nullptr);timer_=lv_timer_create(tick_cb,1000,this);show_favorites();return timer_!=nullptr;}
bool BusApp::onPause(){if(timer_){lv_timer_del(timer_);timer_=nullptr;}bus_service_cancel_all();return true;}
bool BusApp::onResume(){timer_=lv_timer_create(tick_cb,1000,this);show_favorites();return timer_!=nullptr;}
bool BusApp::onDestroy(){bus_service_set_listener(nullptr,nullptr);bus_service_cancel_all();if(timer_){lv_timer_del(timer_);timer_=nullptr;}if(stops_)bus_service_free(stops_);stops_=nullptr;root_=content_=body_=nullptr;return true;}
bool BusApp::onBack(){if(page_==ETA){show_stops();return true;}if(page_==STOPS){show_search();return true;}if(page_==SEARCH){show_favorites();return true;}return CrystalApp::onBack();}
