#!/usr/bin/env python3
"""Regenerate transit_index_data.c from the live KMB and Citybus route lists.

Run by hand, not from the build: a build that depends on a third-party endpoint
being up is a build that fails offline.

    python3 tools/gen_route_index.py --out src/transit_index_data.c

Two objects come out of this, and keeping them apart is the whole point:

  * route names   -- the distinct 1-4 character names over both operators, used
                     by the keypad to grey keys. ~1,050 records, 5 bytes each.
  * KMB variants  -- (route, bound, service_type) triples. KMB has no
                     direction-free /route/{route} endpoint: /route/68X/O/1 is
                     422 "Invalid direction" and only
                     /route/{route}/{outbound|inbound}/{service_type} answers.
                     Service types run 1-9 today, so they cannot be guessed
                     without either probing 18 URLs per lookup or holding this
                     table. 4 bytes per variant.

Neither is the 349 KB route table. The table's origin/destination strings, which
are the bulk of it, are fetched per variant on demand and never stored here.

--fixture reads saved JSON instead of the network so the output is reproducible
offline; --check verifies the committed file matches what the inputs produce.
"""

from __future__ import annotations

import argparse
import datetime
import json
import pathlib
import sys
import urllib.request

KMB_ROUTES = "https://data.etabus.gov.hk/v1/transport/kmb/route/"
CTB_ROUTES = "https://rt.data.gov.hk/v2/transport/citybus/route/CTB"

# Must match transit_routes.c. Space (0x20) sorts below every member, which is
# what makes memcmp over the padded name a total order matching strcmp.
CHARSET = "0123456789ABCDEFGHKMNOPRSTWX"
NAME_LEN = 4
OP_KMB = 1 << 0
OP_CTB = 1 << 1


def fetch(url: str, fixture: pathlib.Path | None) -> dict:
    if fixture is not None:
        return json.loads(fixture.read_text())
    with urllib.request.urlopen(url, timeout=60) as response:
        return json.loads(response.read().decode("utf-8"))


def collect(kmb: dict, ctb: dict) -> tuple[list[tuple[str, int]], list[tuple[str, str, int]]]:
    """Return (sorted [(name, ops)], sorted [(route, bound, service_type)])."""
    ops: dict[str, int] = {}
    variants: set[tuple[str, str, int]] = set()

    for row in kmb.get("data") or []:
        name = str(row["route"]).strip().upper()
        bound = str(row["bound"]).strip().upper()
        service_type = int(str(row["service_type"]).strip())
        ops[name] = ops.get(name, 0) | OP_KMB
        if bound not in ("O", "I"):
            raise SystemExit(f"unexpected KMB bound {bound!r} for route {name}")
        variants.add((name, bound, service_type))

    # Citybus serves one object per route with no direction dimension; both
    # directions exist and are addressed by the words outbound/inbound.
    ctb_data = ctb.get("data") or []
    if isinstance(ctb_data, dict):
        ctb_data = [ctb_data]
    for row in ctb_data:
        name = str(row["route"]).strip().upper()
        ops[name] = ops.get(name, 0) | OP_CTB

    for name in ops:
        if not 1 <= len(name) <= NAME_LEN:
            raise SystemExit(f"route name {name!r} is not 1-{NAME_LEN} characters")
        for char in name:
            if char not in CHARSET:
                raise SystemExit(f"route name {name!r} uses {char!r}, outside the charset")

    for _, _, service_type in variants:
        if not 1 <= service_type <= 255:
            raise SystemExit(f"service_type {service_type} does not fit a uint8_t")

    names = sorted((name.ljust(NAME_LEN), mask) for name, mask in ops.items())
    ordered = sorted(variants, key=lambda v: (v[0].ljust(NAME_LEN), v[1], v[2]))
    return names, ordered


def render(names: list[tuple[str, int]], variants: list[tuple[str, str, int]], source: str) -> str:
    index_of = {name: position for position, (name, _) in enumerate(names)}
    lines: list[str] = []
    add = lines.append

    add("/* SPDX-License-Identifier: PolyForm-Noncommercial-1.0.0 */")
    add("/*")
    add(" * Generated by tools/gen_route_index.py -- do not edit by hand.")
    add(f" * Source: {source}")
    add(f" * Route names: {len(names)}  KMB variants: {len(variants)}")
    add(" */")
    add("")
    add('#include "transit_routes.h"')
    add("")
    add("const char transit_charset[] = \"" + CHARSET + "\";")
    add("")
    add("// Sorted ascending by memcmp over the 4-byte space-padded name.")
    add("const transit_route_name_t transit_route_index[] = {")
    for name, mask in names:
        add(f'    {{{{{", ".join(f"0x{ord(c):02X}" for c in name)}}}, {mask}}},'
            f'  // {name.strip()}')
    add("};")
    add(f"const uint16_t transit_route_index_count = {len(names)};")
    add("")
    add("// Sorted by (name, bound, service_type). name_index refers to the table above.")
    add("const transit_route_variant_t transit_route_variants[] = {")
    for name, bound, service_type in variants:
        padded = name.ljust(NAME_LEN)
        add(f"    {{{index_of[padded]}, '{bound}', {service_type}}},"
            f"  // {name} {bound} {service_type}")
    add("};")
    add(f"const uint16_t transit_route_variant_count = {len(variants)};")
    add("")
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--out", type=pathlib.Path,
                        default=pathlib.Path(__file__).resolve().parents[1] / "src" / "transit_index_data.c")
    parser.add_argument("--kmb-fixture", type=pathlib.Path)
    parser.add_argument("--ctb-fixture", type=pathlib.Path)
    parser.add_argument("--check", action="store_true",
                        help="fail if --out differs from the generated content")
    args = parser.parse_args()

    kmb = fetch(KMB_ROUTES, args.kmb_fixture)
    ctb = fetch(CTB_ROUTES, args.ctb_fixture)
    names, variants = collect(kmb, ctb)

    if args.kmb_fixture or args.ctb_fixture:
        source = "local fixtures"
    else:
        source = f"live endpoints, {datetime.date.today().isoformat()}"
    rendered = render(names, variants, source)

    if args.check:
        existing = args.out.read_text() if args.out.exists() else ""
        # The source line carries a date, so compare everything else.
        strip = lambda text: [l for l in text.splitlines() if not l.startswith(" * Source:")]
        if strip(existing) != strip(rendered):
            print(f"{args.out} is out of date", file=sys.stderr)
            return 1
        print(f"{args.out} matches ({len(names)} names, {len(variants)} variants)")
        return 0

    args.out.write_text(rendered)
    print(f"wrote {args.out}: {len(names)} names, {len(variants)} KMB variants")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
